name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    continue-on-error: ${{ startsWith(matrix.kotlin-version, '1.4.2') }}

    strategy:
      # Run all tasks, even if some fail. Note that they don't share an output, some tasks overlap
      # which is expected. If they need to share their outputs, then we need a proper caching
      # solution.
      fail-fast: false
      matrix:
        gradle-task: [assemble, test, ktlintCheck]
        kotlin-version: [1.3.72, 1.4.10, 1.4.20-dev-3947]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # On Windows the command looks a little bit different. Notice that we use the .bat file and
      # quotes for the Kotlin version, because dots "." in the Kotlin version and parameter name
      # cause issues.
      #
      # Expressions in Github actions are limited. If there would be an if expression, then we
      # wouldn't need to duplicate the next step and depending on the OS enable / disable them.
      - name: ${{ matrix.gradle-task }} with Gradle Ubuntu
        run: ./gradlew ${{ matrix.gradle-task }} --no-build-cache --no-daemon --stacktrace -Psquare.kotlinVersion=${{ matrix.kotlin-version }}
        if: ${{ startsWith(matrix.os, 'ubuntu') }}

      - name: ${{ matrix.gradle-task }} with Gradle Windows
        run: ./gradlew.bat ${{ matrix.gradle-task }} --no-build-cache --no-daemon --stacktrace "-Psquare.kotlinVersion=${{ matrix.kotlin-version }}"
        if: ${{ startsWith(matrix.os, 'windows') }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.gradle-task, 'test') && failure() }}
        with:
          # Use the Kotlin version to prevent overrides.
          name: test-results-${{ matrix.kotlin-version }}
          path: ./**/build/reports/tests/

  build-gradle-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gradle-plugin

    timeout-minutes: 15
    continue-on-error: ${{ startsWith(matrix.kotlin-version, '1.4.2') }}

    strategy:
      # Run all tasks, even if some fail. Note that they don't share an output, some tasks overlap
      # which is expected. If they need to share their outputs, then we need a proper caching
      # solution.
      fail-fast: false
      matrix:
        gradle-task: [test, ktlintCheck]
        kotlin-version: [1.3.72, 1.4.10, 1.4.20-dev-3947]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: ${{ matrix.gradle-task }} with Gradle Ubuntu
        run: ./gradlew ${{ matrix.gradle-task }} --no-build-cache --no-daemon --stacktrace -Psquare.kotlinVersion=${{ matrix.kotlin-version }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.gradle-task, 'test') && failure() }}
        with:
          # Use the Kotlin version to prevent overrides.
          name: test-results-${{ matrix.kotlin-version }}
          path: ./**/build/reports/tests/
